# 선형 연립방정식과 역행렬

In [2]:
import numpy as np

A = np.array([[2, 0, 0],
              [0, 4, 0],
              [0, 0, 5]])
B = np.array([[0.5, 0, 0,],
             [0, 0.25, 0],
             [0, 0, 0.2]])

A @ B

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [4]:
C = np.array([[1, 1, 0],
             [0, 1, 1],
             [1, 1, 1]])
np.linalg.det(C)

1.0

In [9]:
np.linalg.inv(C)

array([[ 0., -1.,  1.],
       [ 1.,  1., -1.],
       [-1.,  0.,  1.]])

In [10]:
A = np.array([[1, 1, 0], [0, 1, 1], [1, 1, 1]])
A

array([[1, 1, 0],
       [0, 1, 1],
       [1, 1, 1]])

In [11]:
Ainv = np.linalg.inv(A)
Ainv

array([[ 0., -1.,  1.],
       [ 1.,  1., -1.],
       [-1.,  0.,  1.]])

In [12]:
b = np.array([[2], [2], [3]])
b

array([[2],
       [2],
       [3]])

In [13]:
x = Ainv @ b
x

array([[1.],
       [1.],
       [1.]])

In [14]:
A @ x - b

array([[0.],
       [0.],
       [0.]])

In [15]:
x, resid, rank, s = np.linalg.lstsq(A, b)
x

C:\Users\admin\AppData\Local\Temp\ipykernel_2460\2281382400.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  x, resid, rank, s = np.linalg.lstsq(A, b)


array([[1.],
       [1.],
       [1.]])

In [17]:
A = np.array([[1, 1, 0], [0, 1, 1], [1, 1, 1], [1, 1, 2]])
A

array([[1, 1, 0],
       [0, 1, 1],
       [1, 1, 1],
       [1, 1, 2]])

In [18]:
b = np.array([[2], [2], [3], [4.1]])
b

array([[2. ],
       [2. ],
       [3. ],
       [4.1]])

In [19]:
Apinv = np.linalg.inv(A.T @ A) @ A.T
Apinv

array([[ 0.33333333, -1.        ,  0.33333333,  0.33333333],
       [ 0.5       ,  1.        ,  0.        , -0.5       ],
       [-0.5       ,  0.        ,  0.        ,  0.5       ]])

In [20]:
x = Apinv @ b
x

array([[1.03333333],
       [0.95      ],
       [1.05      ]])

In [21]:
A @ x

array([[1.98333333],
       [2.        ],
       [3.03333333],
       [4.08333333]])

In [22]:
x, resid, rank, s = np.linalg.lstsq(A, b)
x

C:\Users\admin\AppData\Local\Temp\ipykernel_2460\2281382400.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  x, resid, rank, s = np.linalg.lstsq(A, b)


array([[1.03333333],
       [0.95      ],
       [1.05      ]])

In [23]:
resid, np.linalg.norm(A @ x - b) ** 2

(array([0.00166667]), 0.0016666666666666624)