# 고윳값 분해

In [3]:
import numpy as np

B = np.array([[2, 3], [2, 1]])

lambda1 = 4
v1 =np.array([3/np.sqrt(13), 2 / np.sqrt(13)])

lambda2 = -1
v2 = np.array([-1/np.sqrt(2), 1 / np.sqrt(2)])

print(np.array_equal(B @ v1, lambda1 * v1))
print(np.array_equal(B @ v2, lambda2 * v2))

True
True


In [5]:
A = np.array([[1, -2], [2, -3]])
w1, V1 = np.linalg.eig(A)

print(w1)
print(V1)

[-0.99999998 -1.00000002]
[[0.70710678 0.70710678]
 [0.70710678 0.70710678]]


In [6]:
B = np.array([[2, 3], [2, 1]])
w2, V2 = np.linalg.eig(B)

print(w2)
print(V2)

[ 4. -1.]
[[ 0.83205029 -0.70710678]
 [ 0.5547002   0.70710678]]


In [7]:
C = np.array([[0, -1], [1, 0]])
w3, V3 = np.linalg.eig(C)

print(w3)
print(V3)

[0.+1.j 0.-1.j]
[[0.70710678+0.j         0.70710678-0.j        ]
 [0.        -0.70710678j 0.        +0.70710678j]]


In [8]:
D = np.array([[2, 1], [1, 2]])
w4, V4 = np.linalg.eig(D)
print(w4)
print(V4)

[3. 1.]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [9]:
E = np.array([[2, 3], [2, 1]])
w5, V5 = np.linalg.eig(E)
print(w5)
print(V5)

[ 4. -1.]
[[ 0.83205029 -0.70710678]
 [ 0.5547002   0.70710678]]


In [10]:
V2

array([[ 0.83205029, -0.70710678],
       [ 0.5547002 ,  0.70710678]])

In [12]:
V2_inv = np.linalg.inv(V2)
V2_inv

array([[ 0.72111026,  0.72111026],
       [-0.56568542,  0.84852814]])

In [13]:
V2 @ np.diag(w2) @ V2_inv

array([[2., 3.],
       [2., 1.]])

In [14]:
w, V = np.linalg.eig(np.array([[2, 3], [2, 1]]))
Vinv = np.linalg.inv(V)

print(V)
print(np.diag(w))
print(Vinv)
print(V @ np.diag(w) @ Vinv)

[[ 0.83205029 -0.70710678]
 [ 0.5547002   0.70710678]]
[[ 4.  0.]
 [ 0. -1.]]
[[ 0.72111026  0.72111026]
 [-0.56568542  0.84852814]]
[[2. 3.]
 [2. 1.]]


In [15]:
A = np.array([[2, 3], [2, 1]])
w, V = np.linalg.eig(A)
Vinv = np.linalg.inv(V)
Ainv = V @ np.diag(1 / w) @ Vinv
print(Ainv)

[[-0.25  0.75]
 [ 0.5  -0.5 ]]


In [16]:
np.linalg.inv(A)

array([[-0.25,  0.75],
       [ 0.5 , -0.5 ]])

In [17]:
A = np.array([[60., 30., 20.],
              [30., 20., 15.],
              [20., 15., 12.]])

w, V = np.linalg.eig(A)
w1, w2, w3 = w
v1 = V[:, 0:1]
v2 = V[:, 1:2]
v3 = V[:, 2:3]
A1 = v1 @ v1.T
A2 = v2 @ v2.T
A3 = v3 @ v3.T

In [18]:
w

array([84.49913563,  7.33962395,  0.16124042])

In [19]:
w1

84.49913562741926

In [20]:
A1

array([[0.68400331, 0.38032811, 0.26738233],
       [0.38032811, 0.21147481, 0.14867328],
       [0.26738233, 0.14867328, 0.10452188]])

In [21]:
V

array([[ 0.82704493,  0.54744843,  0.12765933],
       [ 0.4598639 , -0.52829024, -0.71374689],
       [ 0.32329844, -0.64900666,  0.68867153]])

In [22]:
w1 * A1

array([[57.79768857, 32.13739648, 22.59357583],
       [32.13739648, 17.8694387 , 12.56276371],
       [22.59357583, 12.56276371,  8.83200836]])

In [23]:
w2 * A2

array([[ 2.19968372, -2.12270483, -2.60775134],
       [-2.12270483,  2.04841985,  2.51649195],
       [-2.60775134,  2.51649195,  3.09152039]])

In [24]:
w3 * A3

array([[ 0.00262772, -0.01469165,  0.01417551],
       [-0.01469165,  0.08214145, -0.07925566],
       [ 0.01417551, -0.07925566,  0.07647125]])

In [25]:
w1 * A1 + w2 * A2 + w3 * A3

array([[60., 30., 20.],
       [30., 20., 15.],
       [20., 15., 12.]])

In [26]:
np.linalg.inv(A)

array([[ 0.15, -0.6 ,  0.5 ],
       [-0.6 ,  3.2 , -3.  ],
       [ 0.5 , -3.  ,  3.  ]])

In [27]:
1 / w1 * A1

array([[0.0080948 , 0.00450097, 0.00316432],
       [0.00450097, 0.00250269, 0.00175947],
       [0.00316432, 0.00175947, 0.00123696]])

In [28]:
1 / w2 * A2

array([[ 0.04083313, -0.03940415, -0.04840816],
       [-0.03940415,  0.03802519,  0.04671409],
       [-0.04840816,  0.04671409,  0.05738845]])

In [29]:
1 / w3 * A3

array([[ 0.10107208, -0.56509682,  0.54524384],
       [-0.56509682,  3.15947213, -3.04847356],
       [ 0.54524384, -3.04847356,  2.94137459]])

In [30]:
1 / w1 * A1 + 1 / w2 * A2 + 1 / w3 * A3

array([[ 0.15, -0.6 ,  0.5 ],
       [-0.6 ,  3.2 , -3.  ],
       [ 0.5 , -3.  ,  3.  ]])

In [31]:
from sklearn.datasets import load_iris
iris = load_iris()
X = iris.data

In [32]:
X[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [34]:
COV = X.T @ X
COV

array([[5223.85, 2673.43, 3483.76, 1128.14],
       [2673.43, 1430.4 , 1674.3 ,  531.89],
       [3483.76, 1674.3 , 2582.71,  869.11],
       [1128.14,  531.89,  869.11,  302.33]])

In [35]:
w, V = np.linalg.eig(COV)
w

array([9.20830507e+03, 3.15454317e+02, 1.19780429e+01, 3.55257020e+00])

요약: 고유분해의 성질


N차원 정방행렬 A에 대해

행렬 A는 N개의 고윳값-고유벡터를 가진다(복소수인 경우와 중복인 경우를 포함).

행렬의 대각합은 모든 고윳값의 합과 같다.

행렬의 행렬식은 모든 고윳값의 곱과 같다.

행렬 A가 대칭행렬이면 N개의 실수 고윳값을 가지며 고유벡터들이 서로 **직교(orthogonal)**이다.

행렬 A가 대칭행렬이고 고윳값이 모두 양수이면 양의 정부호(positive-definite)이고 역행렬이 존재한다. 역도 성립한다.

행렬 A가 어떤 행렬 X의 분산행렬 XTX이면 0 또는 양의 고윳값을 가진다.

행렬 X∈RN×M(N≥M)가 풀랭크이면 분산행렬 XTX은 역행렬이 존재한다.

